export const projectData = [
  {
    id: 1,
    name: "Watch",
    title: "Watch",
    description: "Construindo um relógio usando html, css e javascript",
    url: "../assets/project-watch.jpeg",
    link: "https://brunofelipehp.github.io/watch/",
    repo: "https://github.com/brunofelipehp/watch",
  },
  {
    id: 2,
    name: "Dashbord",
    title: "Dashbord",
    description: "Construindo um relógio usando html, css e javascript",
    url: "../assets/Dashbord.jpeg",
    link: "https://brunofelipehp.github.io/watch/",
    repo: "https://github.com/brunofelipehp/watch",
  },
  {
    id: 3,
    name: "Movies",
    title: "Movies",
    description: "Construindo um relógio usando html, css e javascript",
    url: "../assets/movies.jpeg",
    link: "https://brunofelipehp.github.io/watch/",
    repo: "https://github.com/brunofelipehp/watch",
  },
  {
    id: 4,
    name: "Watch",
    title: "Watch",
    description: "Construindo um relógio usando html, css e javascript",
    url: "../assets/beauty.jpeg",
    link: "https://brunofelipehp.github.io/watch/",
    repo: "https://github.com/brunofelipehp/watch",
  },
  {
    id: 5,
    name: "Watch",
    title: "Watch",
    description: "Construindo um relógio usando html, css e javascript",
    url: "../assets/project-watch.jpeg",
    link: "https://brunofelipehp.github.io/watch/",
    repo: "https://github.com/brunofelipehp/watch",
  },
  {
    id: 6,
    name: "Watch",
    title: "Watch",
    description: "Construindo um relógio usando html, css e javascript",
    url: "../assets/project-watch.jpeg",
    link: "https://brunofelipehp.github.io/watch/",
    repo: "https://github.com/brunofelipehp/watch",
  },
];
